# Generated by Django 3.2.8 on 2021-10-17 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipeapp', '0007_auto_20211014_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='free',
            field=models.BooleanField(default=True),
        ),
    ]
